# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Latitude55Cli < Formula
  desc ""
  homepage "https://github.com/hloughrey/latitude55-cli"
  version "0.0.7"
  license "MIT"

  on_macos do
    url "https://github.com/hloughrey/latitude55-cli/releases/download/v0.0.7/latitude55-cli_0.0.7_darwin_all.tar.gz"
    sha256 "6bb5ed50b38e62607ae3b252dbfef8ecabf12cab3725bc6ea8f1c80fc1350f87"

    def install
      bin.install "latitude55-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hloughrey/latitude55-cli/releases/download/v0.0.7/latitude55-cli_0.0.7_linux_amd64.tar.gz"
        sha256 "364635e48760716b3979535e8275ea9d7d670458636a553f3752870380b0c117"

        def install
          bin.install "latitude55-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hloughrey/latitude55-cli/releases/download/v0.0.7/latitude55-cli_0.0.7_linux_arm64.tar.gz"
        sha256 "6d627d8561cd82f76e8f5d5c9a3a2f832ccb8930bc4515a5849bed586df70282"

        def install
          bin.install "latitude55-cli"
        end
      end
    end
  end
end
