# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Latitude55Cli < Formula
  desc ""
  homepage "https://github.com/hloughrey/latitude55-cli"
  version "0.0.8"
  license "MIT"

  on_macos do
    url "https://github.com/hloughrey/latitude55-cli/releases/download/v0.0.8/latitude55-cli_0.0.8_darwin_all.tar.gz"
    sha256 "f0c5052802c85bcec6cdea5ac7df482cfc62def43a79073fe4bacec14a1fa79c"

    def install
      bin.install "latitude55-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hloughrey/latitude55-cli/releases/download/v0.0.8/latitude55-cli_0.0.8_linux_amd64.tar.gz"
        sha256 "aadc0ab88b1c2a30623fe78a33561eb4978ba216a84ecfb6cb9761d8e4a3918d"

        def install
          bin.install "latitude55-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hloughrey/latitude55-cli/releases/download/v0.0.8/latitude55-cli_0.0.8_linux_arm64.tar.gz"
        sha256 "38624aa60c746fc137b46ab7b8de79ce7c603c94815727b26230835287632b18"

        def install
          bin.install "latitude55-cli"
        end
      end
    end
  end
end
